# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
  - 1.5
before_script:
  - julia --project=. -e 'using Pkg; Pkg.add(PackageSpec(name="Gridap", rev="master"))'
notifications:
  email:
    on_success: never
    on_failure: always
jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();Pkg.build()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
